In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier  
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, roc_auc_score

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.info()
df.head()

In [4]:
label_encoder = LabelEncoder()
for colum in df.select_dtypes(include=['object']).columns:
    if colum != 'Churn':
        df[colum] = label_encoder.fit_transform(df[colum])

In [5]:
df['Churn'] = label_encoder.fit_transform(df['Churn'])
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5375,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,2505,0
1,3962,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1466,0
2,2564,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,157,1
3,5535,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1400,0
4,6511,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,925,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   int64
 1   gender            7043 non-null   int64
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   int64
 4   Dependents        7043 non-null   int64
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   int64
 7   MultipleLines     7043 non-null   int64
 8   InternetService   7043 non-null   int64
 9   OnlineSecurity    7043 non-null   int64
 10  OnlineBackup      7043 non-null   int64
 11  DeviceProtection  7043 non-null   int64
 12  TechSupport       7043 non-null   int64
 13  StreamingTV       7043 non-null   int64
 14  StreamingMovies   7043 non-null   int64
 15  Contract          7043 non-null   int64
 16  PaperlessBilling  7043 non-null   int64
 17  PaymentMethod     7043 non-null   int64
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   int64
 20  Churn             7043 non-null   int64
dtypes: float64(1), int64(20)
memory usage: 1.1 MB

In [7]:
scaler = StandardScaler()
numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
df[numerical_features]= scaler.fit_transform(df[numerical_features])
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5375,0,0,1,0,-1.277445,0,1,0,0,...,0,0,0,0,0,1,2,-1.160323,-0.398608,0
1,3962,1,0,0,0,0.066327,1,0,0,2,...,2,0,0,0,1,0,3,-0.259629,-0.948762,0
2,2564,1,0,0,0,-1.236724,1,0,0,2,...,0,0,0,0,0,1,3,-0.362660,-1.641883,1
3,5535,1,0,0,0,0.514251,0,1,0,2,...,2,2,0,0,1,0,0,-0.746535,-0.983710,0
4,6511,0,0,0,0,-1.236724,1,0,1,0,...,0,0,0,0,0,1,2,0.197365,-1.235224,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,4853,1,0,1,1,-0.340876,1,2,0,2,...,2,2,2,2,1,1,3,0.665992,-0.879397,0
7039,1525,0,0,1,1,1.613701,1,2,1,0,...,2,0,2,2,1,1,1,1.277533,1.292099,0
7040,3367,0,0,1,1,-0.870241,0,1,0,2,...,0,0,0,0,0,1,2,-1.168632,-0.139680,0
7041,5934,1,1,1,0,-1.155283,1,2,1,0,...,0,0,0,0,0,1,3,0.320338,-0.316534,1
7042,2226,1,0,0,0,1.369379,1,0,1,2,...,2,2,2,2,2,1,0,1.358961,1.138013,0

In [8]:
x = df.drop(columns=['Churn'])
y = df['Churn']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(pd.Series(y_train).value_counts())

Churn
0    4138
1    1496
Name: count, dtype: int64

In [9]:
smote = SMOTE(random_state=42)
x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)
print(pd.Series(y_train_smote).value_counts())

c:\Users\LENOVO\anaconda3\envs\condaenv\lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(

Churn
0    4138
1    4138
Name: count, dtype: int64

In [14]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(x_train, y_train)
pred_rf_model = rf_model.predict(x_test)
print(classification_report(y_test, pred_rf_model))
print(roc_auc_score(y_test, pred_rf_model))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1036
           1       0.66      0.48      0.55       373

    accuracy                           0.80      1409
   macro avg       0.74      0.69      0.71      1409
weighted avg       0.78      0.80      0.78      1409

0.6945795853302557

In [20]:
rf_model_clas = RandomForestClassifier(random_state=42)
rf_model_clas.fit(x_train_smote, y_train_smote)
pred_rf_model_clas = rf_model_clas.predict(x_test)
print(classification_report(y_test, pred_rf_model_clas))
print(roc_auc_score(y_test, rf_model_clas.predict_proba(x_test)[:, 1]))

              precision    recall  f1-score   support

           0       0.85      0.86      0.85      1036
           1       0.60      0.58      0.59       373

    accuracy                           0.78      1409
   macro avg       0.72      0.72      0.72      1409
weighted avg       0.78      0.78      0.78      1409

0.8294818180877161

In [27]:
xg_model = XGBClassifier(eval_metric='logloss', random_state=42)
xg_model.fit(x_train, y_train)
pred_xg = xg_model.predict(x_test)
print(classification_report(y_test, pred_xg))
print(roc_auc_score(y_test, xg_model.predict_proba(x_test)[:, 1]))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      1036
           1       0.62      0.53      0.57       373

    accuracy                           0.79      1409
   macro avg       0.73      0.71      0.72      1409
weighted avg       0.78      0.79      0.78      1409

0.832633763598911

In [ ]:
xg_model_smote = XGBClassifier(eval_metric='logloss', random_state=42)
xg_model_smote.fit(x_train_smote, y_train_smote)
pred_xg_smote = xg_model_smote.predict(x_test)
print(classification_report(y_test, pred_xg_smote))
print(roc_auc_score(y_test, xg_model_smote.predict_proba(x_test)[:, 1]))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85      1036
           1       0.58      0.58      0.58       373

    accuracy                           0.78      1409
   macro avg       0.72      0.72      0.72      1409
weighted avg       0.78      0.78      0.78      1409

0.8311406005775979

In [ ]:
lgb_model = LGBMClassifier(random_state=42)
lgb_model.fit(x_train, y_train)
pred_lgb = lgb_model.predict(x_test)
print(classification_report(y_test, pred_lgb))
print(roc_auc_score(y_test, lgb_model.predict_proba(x_test)[:, 1]))

[LightGBM] [Info] Number of positive: 1496, number of negative: 4138
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003563 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 882
[LightGBM] [Info] Number of data points in the train set: 5634, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.265531 -> initscore=-1.017418
[LightGBM] [Info] Start training from score -1.017418
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1036
           1       0.65      0.54      0.59       373

    accuracy                           0.80      1409
   macro avg       0.75      0.72      0.73      1409
weighted avg       0.79      0.80      0.80      1409

0.8499901663440537

In [ ]:
lgb_model_smote = LGBMClassifier(random_state=42)
lgb_model_smote.fit(x_train_smote, y_train_smote)
pred_lgb_model_smote = lgb_model_smote.predict(x_test)
print(classification_report(y_test, pred_lgb_model_smote))
print(roc_auc_score(y_test, lgb_model_smote.predict_proba(x_test)[:, 1]))

[LightGBM] [Info] Number of positive: 4138, number of negative: 4138
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001857 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1063
[LightGBM] [Info] Number of data points in the train set: 8276, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
              precision    recall  f1-score   support

           0       0.85      0.86      0.86      1036
           1       0.61      0.59      0.60       373

    accuracy                           0.79      1409
   macro avg       0.73      0.73      0.73      1409
weighted avg       0.79      0.79      0.79      1409

0.8458496796298404